### ISSUE TITLE
Issues encountered during setup

### ISSUE THREAD

**Issue by stevenmc** [burzum/cakephp-user-tools#10]
https://github.com/burzum/cakephp-user-tools/blob/master/docs/Tutorials/Quick-Start.md
Refers to \App\Controller\UsersController but this should be \App\src\Controller\UsersController.php
There is also a syntax error on the first code sample on this page - should be } not ); 

After installation, I get these errors:
Notice (8): Undefined index: userData [ROOT/vendor/burzum/cakephp-user-tools/src/View/Helper/AuthHelper.php, line 60]
Notice (8): Undefined index: userData [ROOT/vendor/burzum/cakephp-user-tools/src/View/Helper/AuthHelper.php, line 67]

**Comment by burzum** [comment]
I've updated the documentation [here](https://github.com/burzum/cakephp-user-tools/blob/develop/docs/Tutorials/Quick-Start.md).

The notices: Are you using the master or developer branch?

**Comment by burzum** [comment]
Try it again, should be finally fixed in both branches.

**Comment by mikebirch** [comment]
Documentation still has errors. 
Missing "class" on line 6. 
```class UsersController extends AppController {```
Line 10 should be `}` instead of `);`

I get an error after following the Quick Start tutorial:
Fatal error: [RuntimeException] View var `userData` not present! Please set the auth data to the view. See the documentation. #0 /var/www/domain.com/vendor/burzum/cakephp-user-tools/src/View/Helper/AuthHelper.php(47)

**Comment by burzum** [comment]
I've fixed the documentation you just mentioned. The auth helper was changed 3 days ago. Please update your develop branch. See this commits message for a more detailed explanation. https://github.com/burzum/cakephp-user-tools/commit/ea94156c0dbcaddc79e4f32e242ce41b06ee68e7

Please keep reporting issues I would like to get this polished. I'm using it myself in three projects without issues so far.
