### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by PennyScripter** [burzum/cakephp-user-tools#16]
I am following your code and am a little confused. I have a default cakephp instal and would like to use your plugin. Right now I would like to use the sql as defined as it will work perfect. How do I set this up the best? Do I need a users controller and model?

Also reading through your UserToolComponent.php I see you defined the emails like below.

```
'reset_password' => [
    'method' => 'resetPassword',
    'view' => 'UserTools.UserTools/reset_password',
],
'request_password' => [
    'method' => 'requestPassword',
    'view' => 'UserTools.UserTools/request_password',
],
'verify_email' => [
    'method' => 'verifyEmailToken',
    'view' => 'UserTools.UserTools/verify_email',
],
```
But in the package I see new_password.ctp , password_reset.ctp and verification_email.cp.

**Comment by burzum** [comment]
These are not the emails but the views for the actions.

The component intercepts the request for actions that don't exist in the controller and uses the plugin methods + plugin views for that. What you pasted above is the mapping of the action to the component method + it's view.

**Comment by PennyScripter** [comment]
I have read the readme but could you explain the install for a default cake installation? I added in a example login from their example pages.

**Comment by burzum** [comment]
What exactly is unclear in the documentation? It explains it pretty well I think.

If you have trouble with [composer](https://getcomposer.org/) please check it's documentation. If you don't know how CakePHP plugins work [see this page](http://book.cakephp.org/3.0/en/plugins.html).

I don't mind fixing bugs and giving some community support but if you want personal support feel free to hire me for my usual rate.

**Comment by PennyScripter** [comment]
I tried reaching you by your website but the CAPTCHA won't verify, Are you available for a small task. I am looking for a default cakephp3 install with your user-tools and https://github.com/dereuromark/cakephp-tinyauth

**Comment by burzum** [comment]
Thanks, I've fixed the form, fugly Wordpress, should switch to [Croogo](https://croogo.org/).

I can install TinyAuth for you but this is easy, just configure Auth in your AppController and the plugin will use these settings and not load the Auth component and use it's default settings.

Try using the contact form again, it it *still* doesn't do it's job please let me know. Send me your *exact* requirements so that I can estimate it.
