### ISSUE TITLE
Something wrong in quick start tutorial?

### ISSUE THREAD

**Issue by waltervos** [burzum/cakephp-user-tools#18]
Hi Burzum,

When following the [quick start tutorial](https://github.com/burzum/cakephp-user-tools/blob/master/docs/Tutorials/Quick-Start.md), I get a fatal error upon loading users/register: "Error: Call to a member function user() on a non-object ". The line that causes the problem is `$this->set('userData', $this->Auth->user());`

This a on a fresh CakePHP install, following your documentation, with UserTools RC5 (selected by using your suggested composer requirement).

What am I doing wrong?

**Comment by burzum** [comment]
Make sure your AuthComponent is loaded.

**Comment by waltervos** [comment]
Yeah, I ended up trying that on a hunch, works. Thanks! I've been away from CakePHP for a while and am just figuring things out again. You might consider adding that to the documentation, for people like me ;).

**Comment by burzum** [comment]
The strange thing is the UserTools component should load Auth if not present. Doesn't make much sense because usually you want to configure it different but it was done for the sake of getting it to run "out of the box".

If you like try to debug the components method _setupAuth() or something and see if it gets called at all.

**Comment by burzum** [comment]
I think the problem is that in the initialize() method there is no call to _getAuthObject().

Add _getAuthObject() to my components initialize() and it should work as well without auth loaded before.

**Comment by waltervos** [comment]
Just adding `$this->_getAuthObject();` to the last line of `UserToolComponent::initialize()` doesn't make a difference for me. Was that what you meant?

Maybe it's better to have it not run out of the box? Otherwise, a short addition to the quick start tutorial such as:

Make sure you load the Auth component in src\Controller\AppController.php's initialize method:

```php
public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Auth');
    }
```
