### ISSUE TITLE
won't update last activity

### ISSUE THREAD

**Issue by Adnan0703** [burzum/cakephp-user-tools#20]
This method doesn't do anything.

```
public function updateLastActivity($userId = null, $field = 'last_action', $options = []) {
		$options = Hash::merge($this->_config['updateLastActivity'], $options);
		if ($this->_table->exists([$this->_table->alias() . '.' . $this->_table->primaryKey()])) {
			return $this->_table->updateAll(
				[$field => date($options['dateFormat'])],
				[$this->_table->primaryKey() => $userId]
			);
		}
		return false;
	}
```
This is the reason.
`$this->_table->exists([$this->_table->alias() . '.' . $this->_table->primaryKey()])`

**Comment by burzum** [comment]
Could you please verify that by an unit test? [There is already a test and it passes.](https://github.com/burzum/cakephp-user-tools/blob/master/tests/TestCase/Model/Behavior/UserBehaviorTest.php#L101) I don't see what's wrong with the line you pasted?

**Comment by Adnan0703** [comment]
No condition/value is being passed to `exists`. 
`[$this->_table->alias() . '.' . $this->_table->primaryKey()]` will become something like `['Users.id']`. Shouldn't it be like `['Users.id' => 1]`.

**Comment by burzum** [comment]
Meh, true, you're right, it's fixed. Please let me know if you encounter more problems.
