### ISSUE TITLE
Does this plugin support multiple user roles?

### ISSUE THREAD

**Issue by adam-je** [burzum/cakephp-user-tools#21]
Like 
> admin
>>Manager
>>>User
>>>>etc?
With different access permissions?

**Comment by burzum** [comment]
No it does not. Please read the documentation and a simply look at the source code reveals that it doesn't, there is no "Auth" folder.

You can use this pluing https://github.com/burzum/cakephp-simple-rbac it allows you to define multiple roles, they have to be returned as an array by the users table roles field per default but this is configurable. It's called *simple* for a reason, if you want a role hierarchy with in heritage you might need to look for something else.
