### ISSUE TITLE
Error: Call to a member function user() on boolean

### ISSUE THREAD

**Issue by MrSleeps** [burzum/cakephp-user-tools#25]
I've followed your instructions (I'm just learning cake) to the letter and when I go to /users/register or infact, anything with /users/ I get the following error:

Error: Call to a member function user() on boolean 
File /my/home/dir/src/Controller/UsersController.php 
Line: 16

Any ideas?

**Comment by burzum** [comment]
> Any ideas?

No because this file `/my/home/dir/src/Controller/UsersController.php` is not part of my plugin and I don't know your code...

**Comment by MrSleeps** [comment]
I literally have no code other than your plugin at the moment, 

I was following the install from here 

https://github.com/burzum/cakephp-user-tools/blob/master/docs/Documentation/Installation.md

and then moved on to here

https://github.com/burzum/cakephp-user-tools/blob/master/docs/Tutorials/Quick-Start.md

Where you mention to edit src/Crontroller/UsersController.php ?

**Comment by burzum** [comment]
Well, you need to have a CakePHP application that is using the plugin. You need to add `$this->loadComponent('Auth');` to your AppControllers initialize() method and configure it properly.

I highly recommend you to do the complete blog tutorial of the official CakePHP documentation or you won't have much fun with any plugin or anything of the framework.

If you wish to get a complete walkthrough and personal support to explain you the very basics I don't mind doing that, just not for free. You can contact me if you're interested in personal training, but I'll charge a hourly rate for that.

**Comment by burzum** [comment]
I've updated the documentation to make this more clear. 

Please see https://github.com/burzum/cakephp-user-tools/blob/develop/docs/Tutorials/Quick-Start.md
