### ISSUE TITLE
Advice on configuration

### ISSUE THREAD

**Issue by djonatanb** [burzum/cakephp-user-tools#27]
Hey, I'd like your advice on how to configure it in a case where:
1 - users are only created by an admin
2 - users will access for the first time with the token
3 - users have to create a password on the first access 

I'll also try to integrate tinyauth, will it be a problem if I replace role by role_id and create a separate role table like tinyauth advises ?

Thanks

**Comment by djonatanb** [comment]
in case I use generate pasword, do I have to call it at an after register?

**Comment by burzum** [comment]
1) Disable the action in the component by setting it to false or overload the component or restrict access via Auth to the action
2) Re-use the verification token functionality
3) Re-use and alter the password reset function as needed for that
