### ISSUE TITLE
Weird redirects 

### ISSUE THREAD

**Issue by djonatanb** [burzum/cakephp-user-tools#29]
Something with Auth and the plugin is not working completely fine. 
When I try to go to /users/register I get a redirect to login, even if the user is authenticated. I'm using TinyAuth and CakePHP 3.1.8 

Whenever I try to access /users/register I get a redirect to login (which should redirect to something else as I'm already logged in) 
Whenever I try to access /users/logout I get redirected to the home of the project withou being logged out.

request_password, change_password and login work
register and logout dont

component configuration : 
```
Configure::write('UserTools.Behavior', [
    'useUuid' => false,
    'register' => [
        'verificationExpirationTime' => '+3 days',
    ]
    
]);

Configure::write('UserTools.Component', [
    'actionMap' => [
        'index' => [
            'method' => 'listing',
            'view' => 'index',
        ],
        'register' => [
            'method' => 'register',
            'view' => 'register'
        ],
        'changePassword' => [
            'method' => 'changePassword',
            'view' => 'change_password'
        ],
        'login' => [
            'method' => 'login',
            'view' => 'login',
        ],
        'requestPassword' => [
            'method' => 'requestPassword',
            'view' => 'request_password',
        ],
    ],
]);

Plugin::load('Burzum/UserTools');
``` 
Inside the UserController.
```
   public function initialize() {
        parent::initialize();
        $this->loadComponent('Burzum/UserTools.UserTool');
        $this->loadComponent('RequestHandler');
    }
  public function beforeRender(Event $event) {
        $this->set('userData', $this->Auth->user());
    }

   public function register() {}
   public function change_password() {}
   public function logout() {}
   public function login() {}
```
AppController
```
$this->loadComponent('Auth', [
            'authenticate' => [
                'Form' => [
                    'fields' => ['username' => 'email', 'password' => 'password']
                ]
            ],
            'authError' => 'Did you really think you are allowed to see that?',
            'authorize' => [
                'TinyAuth.Tiny' => [
                    'multiRole' => false
                ]
            ],
            'unauthorizedRedirect' => false
        ]);
```
This is the acl file for tiny auth, I have been trying everything
```
[Users]
*, index, view, register, logout = admin ; Only user role can access index action
changePassword, logout, login, register = * ;
register = admin

[UserTools.UserTools]
* = admin

[UserTools]
* = admin
```

**Comment by burzum** [comment]
Can you please try to add this line and see if it resolves your issue?

```php
   public function initialize() {
        parent::initialize();
        $this->loadComponent('Burzum/UserTools.UserTool');
        $this->loadComponent('RequestHandler');
        // Please add this:
        $this->Auth->allow(['login', 'register']);
    }
```

**Comment by burzum** [comment]
I can't verify your problem. The registration method doesn't have any redirect code that would be triggered by just going to the action via GET. It will only redirect on a successful registration via POST.

I suspect the problem to be something with the Rbac settings or the plugin itself. My *guess* is, that this here *somehow*  might override the settings?

```
[UserTools.UserTools]
* = admin

[UserTools]
* = admin
```

This is not needed as well, the plugin doesn't contain any controller.

**Comment by djonatanb** [comment]
I have just deactivated the tinyauth and still get the same behavior from the logout action.

with 
```
         $this->Auth->allow(['login', 'register','logout']);
```
/register is accessible but logout still redirects to home

**Comment by burzum** [comment]
Logout will basically always redirect to home. Just take a look at the code of the component.

You're trying to access logout() while being **not** logged in? This works as intended in this case? Why would you be able to logout when not being logged in?

**Comment by djonatanb** [comment]
It was a local problem, either by wrong closing lines at the end of view files or by wrong url call inside the js.

**Comment by burzum** [comment]
OK, thank you.
