### ISSUE TITLE
Using controller instead of component

### ISSUE THREAD

**Issue by ayman-alkom** [burzum/cakephp-user-tools#35]
Hi @burzum 
While I am using the plugin I thought about the idea of using a controller instead of component, that may because:

- The code will be more clear short and may more performance.
- The controller can be override a little more easily.
- The component is useful when we use its functions in multi places but here we just need it for our `UsersController`.

I you liked the idea I may help by a PR about this.

**Comment by burzum** [comment]
> The code will be more clear short and may more performance.

Can you provide a benchmark and results or is that just a claim without proof? The reason it is a component is pretty obviously done for a good reason: Just attach it to *any* controller. Reuseability.

> The controller can be override a little more easily

Explain me how extending a controller is more easy than a component. `Foo extends Bar` job done.

> The component is useful when we use its functions in multi places

Like... multiple projects? The reason it is a component is simply reuseability. The old CakeDC plugin was a pain in the ass to override on a controller level. This is another reason it is now a component.

What exactly do you need to extend? The component is very configurable and if that is not enough just extend the component?

**Comment by ayman-alkom** [comment]
> What exactly do you need to extend? The component is very configurable and if that is not enough just extend the component? I don't see the problem.

I didn't mean that there is a problem, I just fount the component script a little complicated and every thing just to extent the controller.

For example: 

- `actionMap` logic 
- `$this->response = $this->_controller->response;` 
- `$this->_controller = $registry->getController();`

sorry if the list is not meaningful enough, I think that I have to implement this idea by myself and then share you the result, then the discuss will be more clear-full 

finally: I would to say that the target of extending ability  is very wonderful and made me leave other plugins and work with this.

**Comment by burzum** [comment]
I agree about the mapping code but this is mostly done to make it work out of the box. Honestly I can't think of many people using it unchanged. The best way to use it is to bake a simple controller and replace the method contents with a call to the corresponding component method. Like I said, if you have suggestions about how to improve it, just tell me.

**Comment by ayman-alkom** [comment]
OK

**Comment by burzum** [comment]
If you check the mailer branch you'll see that I've moved some code into traits and refactored the email sending stuff into a mailer.
