### ISSUE TITLE
getParam used in UserToolComponent.php

### ISSUE THREAD

**Issue by mikebirch** [burzum/cakephp-user-tools#47]
I'm using CakePHP 3.3 and release 1.0.9 creates error: Method getParam does not exist

**Comment by mikebirch** [comment]
I reverted to 1.0.8, which is OK with CakePHP 3.3

**Comment by burzum** [comment]
This should not happen. The release was thought to not break backward compatibility. I'll have to fix it. :(

**Comment by burzum** [comment]
@mikebirch could you please try the `develop` branch? I fixed this and it should be fully compatible with 3.3.

**Comment by burzum** [comment]
@mikebirch sorry, I've screwed up the tag for the version. This was indeed intended to be BC breaking but I tagged it wrong.

Is there something you need for 3.3 that the plugin doesn't provide or something else I can do?
