### ISSUE TITLE
question about prefix routing 

### ISSUE THREAD

**Issue by webdevzone** [burzum/cakephp-user-tools#49]
Hi,
i have my admin theme created as Plugin  
in my AppController i have condition when prefix is admin use the admin theme. So far all good.

but when i access the admin part i see exception 
**Missing Template
Cake\View\Exception\MissingTemplateException**

```
Confirm you have created the file: "Admin/Users/UserTools/login.ctp" in one of the following paths:
/var/www/myapp/src/Template/Admin/Users/UserTools/login.ctp
```

but my theme is in **/var/www/myapp/plugins/Admin/src/**

do you have any documentation or tutorial how to set up this plugin with route prefix ?

**Comment by burzum** [comment]
@webdevzone check https://book.cakephp.org/3.0/en/development/routing.html#prefix-routing

**Comment by burzum** [comment]
@webdevzone feel free to re-open it or ask another question if there is any.
