### ISSUE TITLE
Login not possible after register

### ISSUE THREAD

**Issue by matibaski** [burzum/cakephp-user-tools#50]
Installed `cakephp-user-tools` on a brand new cakephp application `v3.6.10` without any other dependencies. Installed it with your documentation.

Loaded the plugin in `/conf/bootstrap.php` with

    Plugin::load('Burzum/UserTools');

Activated the plugin in `AppController.php` with

    $this->loadComponent('Auth');
    $this->loadComponent('Burzum/UserTools.UserTool');

    $this->Auth->allow([
        'login', 'register', 'add', 'display'
    ]);
    
    public function beforeRender(Event $event) {
        $this->set('userData', $this->Auth->user());
    }

These functions work:
- Register
- Activation Email
-  Reset Password - Enter email
- Reset Password - Receive email
- Reset Password - Set new password

This function does not work:
- Login

After opening the link in the activation email, I get logged in. But when I log out and try to log in again, it just says `Invalid login credentials.`

I don't know what to debug, I don't know where to debug. I tried to debug some of the processes in the `UserToolsComponent.php` but it's just too big.

Maybe a problem with the newest cake version?

**Update**

Found out that I mustn't load the `AuthComponent` in `AppController.php`.

**Comment by burzum** [comment]
It should work with the AuthComponent loaded as well.
