### ISSUE TITLE
Not sending emails

### ISSUE THREAD

**Issue by chav170** [burzum/cakephp-user-tools#9]
I am having issues using the register function, i am not getting the validation email.

Checking the file "src/Model/Behavior/UserBehavior.php", in the function "public function sendEmail($options = [])", i think its missing a line like "return $Email->send();".

The emails are send from this function? or is there any other?

**Comment by burzum** [comment]
Check your email settings, send() will return boolean or the message content in the case of a successful sent email, if not false, so there is no need to return it.

**Comment by burzum** [comment]
Any news on this issue?

**Comment by burzum** [comment]
Closing this because no further feedback was provided.

If you still have issues with this please re-open the ticket and provide some details, thank you.

**Comment by burzum** [comment]
Fixed in https://github.com/burzum/cakephp-user-tools/commit/fe33e764f71cb32d9534d24498230aa9c16b8b6b
